export const GET_ALL_CLASSES = 'GET_ALL_CLASSES';
export const CHANGE_PORTFOLIO_NAME = 'CHANGE_PORTFOLIO_NAME';
export const GET_ALL_AS_OF_DATAS = 'GET_ALL_AS_OF_DATAS';
export const GET_ALL_CSAM_ROWS_FOR_PORTFOLIO = 'GET_ALL_CSAM_ROWS_FOR_PORTFOLIO';
export const GET_ALL_AS_OF_DATAS_MONTHLY_ONLY = 'GET_ALL_AS_OF_DATAS_MONTHLY_ONLY';
export const GET_TZUR_NAV_DETAILS = 'GET_TZUR_NAV_DETAILS';




export const SELECT_AS_OF_DATE_PORTFOLIO_PAGE = 'SELECT_AS_OF_DATE_PORTFOLIO_PAGE';


export const UPLOAD_EXCEL = 'UPLOAD_EXCEL';
export const CONVER_EXCEL_TO_CSAMROW = 'CONVER_EXCEL_TO_CSAMROW';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';


export const UPDATE_NAV_DATA_TO_PORTFOLIO = 'UPDATE_NAV_DATA_TO_PORTFOLIO';
export const ALL_PORTFOLIOS_ASSETS_AMOUNT = 'ALL_PORTFOLIOS_ASSETS_AMOUNT';
export const UPDATE_CLO_LIST = 'UPDATE_CLO_LIST';
export const UPDATE_CHOOSEN_CLO_LIST = 'UPDATE_CHOOSEN_CLO_LIST';

export const BRING_ALL_CSAM_ROWS = 'BRING_ALL_CSAM_ROWS';
export const BRING__CSAM_ROWS_BY_MONTH = 'BRING__CSAM_ROWS_BY_MONTH';
export const REPOSITORY_ALL_ASOFDATES = 'REPOSITORY_ALL_ASOFDATES';


export const INSERT_MOVEMENTS = 'INSERT_MOVEMENTS';
export const GET_FX_USD = 'GET_FX_USD';


export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_RESET = 'AUTH_RESET'

export const IMPORT_ALL_TZUR = 'IMPORT_ALL_TZUR'