export const GET_ALL_CLASSES = 'GET_ALL_CLASSES';
export const CHANGE_PORTFOLIO_NAME = 'CHANGE_PORTFOLIO_NAME';
export const GET_ALL_AS_OF_DATAS = 'GET_ALL_AS_OF_DATAS';
export const GET_ALL_CSAM_ROWS_FOR_PORTFOLIO = 'GET_ALL_CSAM_ROWS_FOR_PORTFOLIO';




export const SELECT_AS_OF_DATE_PORTFOLIO_PAGE = 'SELECT_AS_OF_DATE_PORTFOLIO_PAGE';


export const UPLOAD_EXCEL = 'UPLOAD_EXCEL';
export const CONVER_EXCEL_TO_CSAMROW = 'CONVER_EXCEL_TO_CSAMROW';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';


export const UPDATE_NAV_DATA_TO_PORTFOLIO = 'UPDATE_NAV_DATA_TO_PORTFOLIO';
export const ALL_PORTFOLIOS_ASSETS_AMOUNT = 'ALL_PORTFOLIOS_ASSETS_AMOUNT';
export const UPDATE_CLO_LIST = 'UPDATE_CLO_LIST';
export const UPDATE_CHOOSEN_CLO_LIST = 'UPDATE_CHOOSEN_CLO_LIST';
